#!/usr/bin/env bash
# bundle_files.sh
# Bundles all files from a folder into a single .md file for AI project knowledge (e.g. Claude, ChatGPT, Gemini).
# With --by-extension, creates one .md per file extension in a new folder.
# With --suffix <name>, adds a suffix to all output filenames.
# With --max-size <kb>, splits output into numbered files if size limit is exceeded.
# Run this after cleanup_copied_files.sh.

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────
SOURCE_DIR="${1:-}"
BY_EXTENSION=false
OUTPUT_FILE=""
MAX_SIZE_KB=0  # 0 = no limit
SUFFIX=""

shift || true
while [[ $# -gt 0 ]]; do
    case "$1" in
        --by-extension) BY_EXTENSION=true ;;
        --max-size)
            shift
            MAX_SIZE_KB="${1:-0}"
            ;;
        --suffix)
            shift
            SUFFIX="_${1:-}"
            ;;
        *) OUTPUT_FILE="$1" ;;
    esac
    shift
done
# ─────────────────────────────────────────────────────────────────────────────

if [[ -z "$SOURCE_DIR" ]]; then
    echo "Error: Please provide a folder to bundle." >&2
    echo "Usage: ./bundle_files.sh <folder> [output_file.md] [--by-extension] [--max-size <kb>]" >&2
    exit 1
fi

if [[ ! -d "$SOURCE_DIR" ]]; then
    echo "Error: '$SOURCE_DIR' is not a valid directory." >&2
    exit 1
fi

SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
FOLDER_NAME="$(basename "$SOURCE_DIR")"

# ── Detect language for code block ───────────────────────────────────────────
get_language() {
    local file="$1"
    local ext="${file##*.}"
    ext="${ext,,}"
    case "$ext" in
        ts|tsx)       echo "tsx" ;;
        js|jsx)       echo "jsx" ;;
        css)          echo "css" ;;
        scss|sass)    echo "scss" ;;
        html)         echo "html" ;;
        json)         echo "json" ;;
        xml)          echo "xml" ;;
        md)           echo "markdown" ;;
        py)           echo "python" ;;
        sh|bash)      echo "bash" ;;
        cs)           echo "csharp" ;;
        java)         echo "java" ;;
        go)           echo "go" ;;
        rs)           echo "rust" ;;
        sql)          echo "sql" ;;
        yaml|yml)     echo "yaml" ;;
        toml)         echo "toml" ;;
        env)          echo "bash" ;;
        txt)          echo "text" ;;
        *)            echo "" ;;
    esac
}

# ── Build a file block as a string ───────────────────────────────────────────
build_block() {
    local file="$1"
    local relative_path="${file#$SOURCE_DIR/}"
    local lang
    lang="$(get_language "$file")"

    printf '%s\n' "---" "## ${relative_path}" "---" "\`\`\`${lang}"
    cat "$file"
    printf '\n%s\n\n' '```'
}

# ── Write to file, split if max size exceeded ─────────────────────────────────
current_part=1
write_block_to() {
    local block="$1"
    local base_name="$2"

    # Determine current output filename
    if [[ "$MAX_SIZE_KB" -gt 0 ]]; then
        current_file="${base_name}_${current_part}.md"
    else
        current_file="${base_name}.md"
    fi

    # Initialize file with header if it doesn't exist
    if [[ ! -f "$current_file" ]]; then
        {
            echo "# ${FOLDER_NAME} — bundled files (part ${current_part})"
            echo "# Generated by bundle_files.sh on $(date '+%Y-%m-%d')"
            echo ""
        } > "$current_file"
    fi

    # Check if adding this block would exceed max size
    if [[ "$MAX_SIZE_KB" -gt 0 ]]; then
        current_size_kb=$(( $(wc -c < "$current_file") / 1024 ))
        block_size_kb=$(( ${#block} / 1024 ))
        if (( current_size_kb + block_size_kb >= MAX_SIZE_KB )); then
            current_part=$(( current_part + 1 ))
            current_file="${base_name}_${current_part}.md"
            {
                echo "# ${FOLDER_NAME} — bundled files (part ${current_part})"
                echo "# Generated by bundle_files.sh on $(date '+%Y-%m-%d')"
                echo ""
            } > "$current_file"
        fi
    fi

    echo "$block" >> "$current_file"
    echo "$current_file"
}

# ── Bundle files ──────────────────────────────────────────────────────────────
bundle_files() {
    local base_name="$1"
    local filter_ext="${2:-}"  # optional: only bundle files with this extension

    local bundled=0
    local skipped=0

    while IFS= read -r -d '' file; do
        relative_path="${file#$SOURCE_DIR/}"

        # Filter by extension if specified
        if [[ -n "$filter_ext" ]]; then
            filename="$(basename "$file")"
            ext="${filename##*.}"
            # Must mirror the extension-collection logic below. Without this,
            # extensionless files match no bucket and are silently dropped.
            [[ "$filename" == "$ext" ]] && ext="no_extension"
            ext="${ext,,}"
            [[ "$ext" != "$filter_ext" ]] && continue
        fi

        # Skip binary files. -b prints the type only; without it the file's
        # own path is part of the matched string, so any file inside a
        # directory whose name contains "text" is misdetected as text.
        if ! file -b "$file" | grep -qE 'text|empty|JSON|ASCII'; then
            echo "  [SKIP]     $relative_path  (binary)" >&2
            (( skipped++ )) || true
            continue
        fi

        block="$(build_block "$file")"
        out="$(write_block_to "$block" "$base_name")"
        echo "  [BUNDLED]  $relative_path → $(basename "$out")" >&2
        (( bundled++ )) || true

    done < <(find "$SOURCE_DIR" -type f -print0 | sort -z)

    echo "$bundled $skipped"
}

# ── MODE: single .md ─────────────────────────────────────────────────────────
if [[ "$BY_EXTENSION" == false ]]; then
    OUTPUT_DIR="${FOLDER_NAME}_bundled"

    if [[ -e "$OUTPUT_DIR" ]]; then
        echo "Error: '$OUTPUT_DIR' already exists." >&2
        exit 1
    fi

    mkdir "$OUTPUT_DIR"

    BASE_NAME="${OUTPUT_FILE:-$FOLDER_NAME}"
    BASE_NAME="${BASE_NAME%.md}"  # strip .md if provided
    BASE_NAME="${OUTPUT_DIR}/${BASE_NAME}${SUFFIX}"

    echo "Source directory : $SOURCE_DIR"
    echo "Output folder    : $OUTPUT_DIR"
    [[ "$MAX_SIZE_KB" -gt 0 ]] && echo "Max file size    : ${MAX_SIZE_KB}KB"
    [[ -n "$SUFFIX" ]] && echo "Suffix           : ${SUFFIX#_}"
    echo ""

    read -r bundled skipped <<< "$(bundle_files "$BASE_NAME")"

    # If no splitting occurred, remove the _1 suffix
    if [[ -f "${BASE_NAME}_1.md" && ! -f "${BASE_NAME}_2.md" ]]; then
        mv "${BASE_NAME}_1.md" "${BASE_NAME}.md"
    fi

    echo ""
    echo "───────────────────────────────────"
    echo "Done. Bundled: $bundled  |  Skipped: $skipped binary file(s)"
    echo "Output folder: $OUTPUT_DIR"
fi

# ── MODE: one .md per extension ──────────────────────────────────────────────
if [[ "$BY_EXTENSION" == true ]]; then
    OUTPUT_DIR="${FOLDER_NAME}_bundled"

    if [[ -e "$OUTPUT_DIR" ]]; then
        echo "Error: '$OUTPUT_DIR' already exists." >&2
        exit 1
    fi

    mkdir "$OUTPUT_DIR"

    echo "Source directory : $SOURCE_DIR"
    echo "Output folder    : $OUTPUT_DIR"
    [[ "$MAX_SIZE_KB" -gt 0 ]] && echo "Max file size    : ${MAX_SIZE_KB}KB"
    [[ -n "$SUFFIX" ]] && echo "Suffix           : ${SUFFIX#_}"
    echo ""

    # Collect all unique extensions
    declare -A seen_exts
    while IFS= read -r -d '' file; do
        filename="$(basename "$file")"
        ext="${filename##*.}"
        [[ "$filename" == "$ext" ]] && ext="no_extension"
        ext="${ext,,}"   # one bucket per extension, regardless of its case
        seen_exts["$ext"]=1
    done < <(find "$SOURCE_DIR" -type f -print0)

    total_bundled=0
    total_skipped=0

    for ext in "${!seen_exts[@]}"; do
        current_part=1
        read -r bundled skipped <<< "$(bundle_files "$OUTPUT_DIR/${ext}${SUFFIX}" "$ext")"

        # If no splitting occurred, remove the _1 suffix
        if [[ -f "${OUTPUT_DIR}/${ext}${SUFFIX}_1.md" && ! -f "${OUTPUT_DIR}/${ext}${SUFFIX}_2.md" ]]; then
            mv "${OUTPUT_DIR}/${ext}${SUFFIX}_1.md" "${OUTPUT_DIR}/${ext}${SUFFIX}.md"
        fi

        (( total_bundled += bundled )) || true
        (( total_skipped += skipped )) || true
    done

    echo ""
    echo "───────────────────────────────────"
    echo "Done. Bundled: $total_bundled  |  Skipped: $total_skipped binary file(s)"
    echo "Output folder: $OUTPUT_DIR"
fi
